### ISSUE TITLE
Consider updating Clojars with more recent fixes

### ISSUE THREAD

**Issue by budstein** [owainlewis/clojure-mail#20]
I just ran into the now-closed issue 15 for clojure-mail using the version currently on Clojars (0.1.6). I've gotten around it now, but wanted to suggest updating the Clojars copy so that the fix is available using "normal" means. Thanks for maintaining a useful library.

**Comment by owainlewis** [comment]
Hi. Good point. I have pushed a new version to Clojars. I changed to group ID so the new version is now at 

```
[io.forward/clojure-mail "1.0"]
```
