### ISSUE TITLE
Folder support?

### ISSUE THREAD

**Issue by ikarth** [owainlewis/clojure-mail#23]
I can get a list of folders with `(clojure-mail.core/folders clojure-mail.core/*store*)` but I'm having trouble accessing anything other than the ones in the `gmail-folder-names` keywords. I know that `(open-folder)` restricts access to only those folders, but it looks like there's no support in clojure-mail for accessing other folders?

**Comment by ikarth** [comment]
I wrote my own version of open-folder, but are there any plans for official support? I don't mind hacking around with the guts of the library, but it'd obviously be better if I was using the public API.

**Comment by shmish111** [comment]
@ikarth, @owainlewis accepted the PR https://github.com/owainlewis/clojure-mail/pull/26 from me which makes things a little less 'gmaily' for those who need something more general.

**Comment by ikarth** [comment]
I'll have to try it out, but this does look like it deals with the issues I was having.
