### ISSUE TITLE
Update clojars artifact to roll in last 6 months' fixes & changes

### ISSUE THREAD

**Issue by russellwhitaker** [owainlewis/clojure-mail#48]
Looks like a few substantive changes & fixes have been rolled in since December; would you mind please bumping the version and deploying an associated artifact to Clojars? I, for one, would greatly appreciate it, thanks in advance.

**Comment by owainlewis** [comment]
Sorry you're right. Need to do a release.

**Comment by russellwhitaker** [comment]
@owainlewis thanks! That would be great; using your lib at work. Speaking of which, are you open to considering pull requests in the near future?

**Comment by owainlewis** [comment]
Hi. Yeah always happy to accept any pull requests. Feel free :+1:

**Comment by owainlewis** [comment]
Version 1.0.5 released. https://clojars.org/io.forward/clojure-mail

Let me know if you need anything else. Thanks

**Comment by russellwhitaker** [comment]
Thanks @owainlewis !
