### ISSUE TITLE
Unable to find static field in com.sun.mail.imap.IMAPFolder$FetchProfileItem

### ISSUE THREAD

**Issue by nrakochy** [owainlewis/clojure-mail#54]
Hello there. 

I added `clojure-mail` to my project and am now unable to compile the project. I ran across this [similar bug report](https://kenai.com/bugzilla/show_bug.cgi?id=8389) which might be helpful.

Attached are a few screenshots. I'm not sure if this is user error (me) or a bug further upstream, and I would appreciate any insight which you might have to sort it out. Many thanks.

Runtime Exception:
![imap_exception](https://cloud.githubusercontent.com/assets/3740177/21671662/724aa122-d2e2-11e6-97b0-8e33f9917a83.png)

Project ns:
![email_parser](https://cloud.githubusercontent.com/assets/3740177/21671805/8880d938-d2e3-11e6-91b3-f8591b4fbbf5.png)

Maven repo locally installed:
![mvn_clojure_mail](https://cloud.githubusercontent.com/assets/3740177/21671634/4fc2a406-d2e2-11e6-837f-b14f3176bf94.png)

**Comment by pmensik** [comment]
I can confirm I am having the same issue.

**Comment by spicalous** [comment]
@nrakochy @pmensik Try running `lein deps :tree` in your project directory and ensure that you are using at least version 1.5.2 of `com.sun.mail/javax.mail`

`FetchProfileItem.MESSAGE` was added in version 1.5.2

https://javamail.java.net/nonav/docs/api/com/sun/mail/imap/IMAPFolder.FetchProfileItem.html#MESSAGE

**Comment by nrakochy** [comment]
Thanks @spicalous. I think your last comment might do the trick. I am using `postal` which is using `javax.mail 1.5.5` whereas `clojure-mail` is on `1.5.4` at the moment.
